Active: false
Enabled: false
Raffle:
  Fund: 0
  DonationFunded: 0
  TicketPrice: 0
  BuyLimit: 0
  PlayerTickets: {}
  PlayerMoneyEntered: {}
Database:
  User: username
  Password: password
  DatabaseName: dbname
  Port: 9999
  Hostname: rolyd.com